### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by Rockybilly** [zhangshun97/Lock-free-Red-black-tree#3]
Greetings,
Your project seems to be a hard worked and genuine one. Given that you decided to share the code, could you please add an open source license to it ? Leaving it without a license, makes it impossible for other people to use your code in their projects that they want to share or distribute (because the details of the copyright license are unknown). 

Cheers. Thanks for the good work.

**Comment by zhangshun97** [comment]
Hi Rockybilly,
Thank you for your kind reminder. The Apache license has been added to this project.

**Comment by Rockybilly** [comment]
You may want to update the corresponding parts of the license text to inform who is the copyright holder (maybe Shun Zhang and Guancheng Li).

Some example project: https://github.com/moby/moby/blob/master/LICENSE

**Comment by zhangshun97** [comment]
Yes, sure. Now I have our names on it :)
Thanks again for your kindness!

**Comment by Rockybilly** [comment]
You're welcome, keep up the good work :)
